### PR TITLE
Fix gtk-3 theme not found by gnome-tweak-tool

### PR DESCRIPTION
**Pull request by HeikoAdams**
The version specific gtk-3.0 themes are not found by gnome-tweak-tool if they are not below a gtk-3.0 directory.

### CODE REVIEW

**Comment by tista500** [comment]
did you read my post?
https://github.com/tista500/Adapta/issues/27

and sub-directory will break in future...

**Comment by HeikoAdams** [comment]
I'm sorry, I did read it

**Comment by pschichtel** [comment]
@tista500 you could add information like that to the CONTRIBUTING.md, so people will see when creating PR's.
Issues are probably not the best place for "announcements"

**Comment by tista500** [comment]
NO.
Because I've already informed that in README.md. Why I should dup such info?
And contributors also should track the upstream Gnome's changes by yourself instead of theme designer.

Regards.

**Pull request closed without merging**
