### PR TITLE
Update App Overview icon in Dash to Android Marshmallow style

### PR DESCRIPTION
**Pull request by HEXcube**
- SVG icon recreated from Marshmallow's original icon: https://android.googlesource.com/platform/packages/apps/Launcher3/+/marshmallow-release/res/drawable-xxhdpi/ic_allapps.png

### CODE REVIEW

**Comment by tista500** [comment]
?? :(

Just to be clear:
* Which apps you used to draw those svgs?
* What type of those pixmap's license was?
* Why those had raised materials with embedded shadows exposed from top-left to bottom-right?

Regards.

**Comment by tista500** [comment]
Rewritten from scratch: https://github.com/tista500/Adapta/commit/fb7a025964cd6c038022ba06e1af63fd1357fc8c

Isn't enough?

Regards.

**Comment by HEXcube** [comment]
> Which apps you used to draw those svgs?

I used Inkscape :relaxed:

> What type of those pixmap's license was?

[Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0) like the rest of Android

> Why those had raised materials with embedded shadows exposed from top-left to bottom-right?

Well, that's a bug with GNOME's renderer. I thought I made adjustments to workaround that. :sweat_smile: It's supposed to look like this: https://github.com/HEXcube/Adapta/blob/master/gnome-shell/assets/show-apps-active.svg and https://github.com/HEXcube/Adapta/blob/master/gnome-shell/assets/show-apps.svg

**Comment by HEXcube** [comment]
> Rewritten from scratch: fb7a025
> 
> Isn't enough?

Updated from PPA this morning and got the new update. Looks cool! :relaxed:

normal

Had a look at https://github.com/tista500/Adapta/commit/10ec6c38bbb9f25057771bdffd2d300cfefd6e7d . Creating shadow with CSS (instead of SVG) was a good move! :smiley:

**Pull request closed without merging**
